### ISSUE TITLE
Add postgreSQL adapter

### ISSUE THREAD

**Issue by davydovanton** [hanami/events#56]

**Comment by russo-matrosso** [comment]
Hi! I'm working on this issue now and found a problem.
Postgress don't assume dots and especially patterns in its channel mechanism. So this library's [feature](https://github.com/hanami/events#patterns) and familiar naming like 'user.created' are not available.
So the question is: is it OK to add a postgreSQL adapter with such limitations?

**Comment by davydovanton** [comment]
I think we can create new issue with custom separator :)

Something like:
```ruby
event = Event.new(:memory, seporator: '_') # => will allow to use user_created event names
```

WDYT?

**Comment by russo-matrosso** [comment]
Well, I found a way to make naming like 'user.created' available. But still, no patterns :(
https://github.com/hanami/events/pull/67

**Comment by davydovanton** [comment]
Hey, sorry but after discussion with @jodosha, we decide to make hanami-events as a pub/sub lib with simple memory and redis adapters only. That's why I should close this issue. I'm sorry for spending you time with it 😞

**Comment by joelvh** [comment]
hi @davydovanton I'm new to Hanami and very interested in this aspect of the framework. I use Wisper currently, and gathered that Hanami has removed Wisper in favor of a custom event API. Where is the best place to see the current status/roadmap/thoughts on this event-driven architecture for Hanami? Happy to contribute as well. Thanks!

**Comment by davydovanton** [comment]
hey, yep, we want to create pub/sup system without global state and with adapters (and ability to use custom adapters). I'm thinking about roadmap and I hope, I'll create it soon 👍

**Comment by russo-matrosso** [comment]
The ability to use custom adapters would be nice!

**Comment by jodosha** [comment]
Folks, what I'd love you to figure out is: how to make `hanami-events` capable to use third-party adapters like PG, or any other data store. Thanks in advance.

**Comment by russo-matrosso** [comment]
Well, I'll just make a separate PG adapter for hanami-events
I think it would be OK. You'll have freedom to introduce new features, and if someone would like to use a bit cutted, but functionable adapter - that would be OK too.

**Comment by joelvh** [comment]
Curious what lead to move away from something simple like Wisper, where anyone can customize the implementation without Hanami having to be bogged down with building and maintaining those things? Thanks.

**Comment by jodosha** [comment]
@joelvh I'm not sure I understood the question. WDYM? Thanks 😄

**Comment by joelvh** [comment]
@jodosha I was just suggesting to introduce some pub/sub API and allow it to be configurable/modular so developers can worry about creating their own "backends". Wisper was great to have a light pub/sub out-of-the-box and you can use other extensions/plugins to integrate with Sidekiq or other things. I don't know the reasoning for Hanami to move away from Wisper, but rebuilding it and also having to maintain various types of backends seems like a lot of work to take on?

Just my 2 cents. New to Hanami and look forward to lending a hand.
