### ISSUE TITLE
Idea: Instrumenters as in rails notification

### ISSUE THREAD

**Issue by davydovanton** [hanami/events#81]
I found `Instrumenters` from [rails guides](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html)

```ruby
ActiveSupport::Notifications.instrument('render', extra: :information) do
  render plain: 'Foo'
end
# send event 'render' after block call
```

And that's why I have a question: should we create something like this? I think it will be great for monitoring. Or we can create hanami-monitoring library (like in dry) and make this repository clear. WDYT?

**Comment by davydovanton** [comment]
cc @jodosha

**Comment by jodosha** [comment]
@davydovanton Sorry if I'm late to comment this, but we already discussed in a 1:1 call. We can have this implemented in `hanami-utils`, so we don't have to bring a dependency of `hanami-events` for all the `hanami-*` gems.

**Comment by davydovanton** [comment]
yep, I just forgot to update this issue. Will do it now, thanks! <3
